CREATE TABLE properties (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date_created TIMESTAMP DEFAULT NOW() NOT NULL,
    listing_status TEXT NOT NULL,
    street_address TEXT NOT NULL,
    city TEXT NOT NULL,
    state_code CHAR(2) NOT NULL,
    zip_code TEXT,
    open_house_time TIME,
    open_house_date DATE,
    price INT
)