CREATE TABLE brokerages (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date_created TIMESTAMP DEFAULT NOW() NOT NULL,
    name TEXT NOT NULL,
    license TEXT NOT NULL,
    street_address TEXT,
    city TEXT,
    state_code CHAR(2),
    zip_code TEXT,
    logo TEXT
)